export const GET_BOOKS_LIST = "GET_BOOKS_LIST";
export const GET_BOOKS_LIST_SUCCESS = "GET_BOOKS_LIST_SUCCESS";
export const GET_BOOKS_LIST_FAILURE = "GET_BOOKS_LIST_FAILURE";

export const ADD_BOOK = "ADD_BOOK";
export const ADD_BOOK_SUCCESS = "ADD_BOOK_SUCCESS";
export const ADD_BOOK_FAILURE = "ADD_BOOK_FAILURE";


export const GET_BOOK = "GET_BOOK";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILURE = "GET_BOOK_FAILURE";

export const UPDATE_BOOK = "UPDATE_BOOK";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_FAILURE = "UPDATE_BOOK_FAILURE";

export const DELETE_BOOK = "DELETE_BOOK";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";

export const SEARCH_BOOKS_LIST = "SEARCH_BOOKS_LIST";
export const SEARCH_BOOKS_LIST_SUCCESS = "SEARCH_BOOKS_LIST_SUCCESS";
export const SEARCH_BOOKS_LIST_FAILURE = "SEARCH_BOOKS_LIST_FAILURE";

export const GET_BOOK_FILTERS_LIST = "GET_BOOK_FILTERS_LIST";
export const GET_BOOK_FILTERS_LIST_SUCCESS = "GET_BOOK_FILTERS_LIST_SUCCESS";
export const GET_BOOK_FILTERS_LIST_FAILURE = "GET_BOOK_FILTERS_LIST_FAILURE";